/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/alimentacao` | `/alimentacao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/compras` | `/compras`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/entreterimento` | `/entreterimento`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/saude` | `/saude`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/transporte` | `/transporte`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calculadora` | `/calculadora`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orcamentos` | `/orcamentos`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(outros)'}/alimentacao` | `/alimentacao`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(outros)'}/compras` | `/compras`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(outros)'}/entreterimento` | `/entreterimento`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(outros)'}/saude` | `/saude`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(outros)'}/transporte` | `/transporte`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calculadora` | `/calculadora`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orcamentos` | `/orcamentos`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cadastro${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(outros)'}/alimentacao${`?${string}` | `#${string}` | ''}` | `/alimentacao${`?${string}` | `#${string}` | ''}` | `${'/(outros)'}/compras${`?${string}` | `#${string}` | ''}` | `/compras${`?${string}` | `#${string}` | ''}` | `${'/(outros)'}/entreterimento${`?${string}` | `#${string}` | ''}` | `/entreterimento${`?${string}` | `#${string}` | ''}` | `${'/(outros)'}/saude${`?${string}` | `#${string}` | ''}` | `/saude${`?${string}` | `#${string}` | ''}` | `${'/(outros)'}/transporte${`?${string}` | `#${string}` | ''}` | `/transporte${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calculadora${`?${string}` | `#${string}` | ''}` | `/calculadora${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configuracoes${`?${string}` | `#${string}` | ''}` | `/configuracoes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orcamentos${`?${string}` | `#${string}` | ''}` | `/orcamentos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/alimentacao` | `/alimentacao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/compras` | `/compras`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/entreterimento` | `/entreterimento`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/saude` | `/saude`; params?: Router.UnknownInputParams; } | { pathname: `${'/(outros)'}/transporte` | `/transporte`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calculadora` | `/calculadora`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orcamentos` | `/orcamentos`; params?: Router.UnknownInputParams; };
    }
  }
}
